# Generated by Django 5.2 on 2025-04-10 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_rename_owner_cart_user_rename_owner_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_created',
            new_name='product_created_date',
        ),
    ]
