# Generated by Django 5.2 on 2025-04-13 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_rename_user_cart_product_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='review_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_connect_product', to='store_app.product'),
        ),
    ]
