# Generated by Django 5.2 on 2025-04-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_rename_cart_owner_cart_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_file',
            field=models.FileField(blank=True, null=True, upload_to='category_icons/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/'),
        ),
    ]
