# Generated by Django 5.2 on 2025-04-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_rename_date_created_product_product_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='product_owner',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='product_owner',
        ),
    ]
