# Generated by Django 5.2 on 2025-04-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0002_rename_name_category_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='item_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='favoriteitem',
            old_name='favorite_cart',
            new_name='carts',
        ),
        migrations.RenameField(
            model_name='favoriteitem',
            old_name='product',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_created_date',
            new_name='account_created_date',
        ),
    ]
